### ISSUE TITLE
Midi over USB

### ISSUE THREAD

**Issue by cosmic-desolation** [zeroerrequattro/arduinoboy-micro#1]
Hi, awesome that you adapted the code to the atmega32u4!

Im very new to this, but if I understand correctly, the atmega32u4 supports midi over usb?

And could the code be changed for that purpose?

As for my project, I don't have any use for dedicated midi connectors, and it would only lead to having a adapter back to usb..

**Comment by 256k** [comment]
BUMP

**Comment by zeroerrequattro** [comment]
Hey there, sorry for the very belated response.
Yes, atmega32u4 supports MIDI over USB features. But this project is very old an not mantained anymore.
The original project I forked 6 years ago made huge steps to include compatibility for a lot of chipsets and is still mantained, I suggest to look directly onto it:

[https://github.com/trash80/Arduinoboy](https://github.com/trash80/Arduinoboy)

I took a look and it supports also MIDI over USB for the atmega32u4.
Hope it helps
